exports.routeParams = [
  {
    route: "auth/send-otp",
    params: { email: "" },
    queryParams: [],
    authRequired: true,
    method: "post",
    tag: "Auth",
  },
  {
    route: "auth/verify-otp",
    params: { email: "", otp: "" },
    queryParams: [],
    authRequired: false,
    method: "post",
    tag: "Auth",
  },
  {
    route: "auth/login",
    params: { email: "", password: "" },
    queryParams: [],
    authRequired: true,
    method: "post",
    tag: "Auth",
  },
  {
    route: "auth/signup",
    params: { fullName: "", email: "", password: "", phoneNumber: "", timezone: "" },
    queryParams: [],
    authRequired: true,
    method: "post",
    tag: "Auth",
  },
  {
    route: "auth/update",
    params: { fullName: "", email: "", password: "", phoneNumber: "", timezone: "", photoUrl: "", stripeCustomerId: "" },
    queryParams: [],
    authRequired: true,
    method: "put",
    tag: "Auth",
  },
  {
    route: "auth/{id}",
    params: {},
    queryParams: [{ name: "id", type: "integer", required: true, in: "path" }],
    method: "delete",
    authRequired: true,
    tag: "Auth",
  }
];
