// Content for fields.js

exports.routeParams = [
  {
    route: "userDetail/update",
    params: {
      gender: "",
      dob: "",
      height: "",
      heightUnit: "",
      weight: "",
      weightUnit: "",
      waist: "",
      waistUnit: "",
    },
    queryParams: [],
    authRequired: true,
    method: "post",
    tag: "User Detail",
  },
  {
    route: "userDetail/address/update",
    params: {
      country: "",
      state: "",
      city: "",
      zip: "",
      lat: "",
      lng: "",
      address: "",
    },
    queryParams: [],
    authRequired: true,
    method: "post",
    tag: "User Detail",
  },
  {
    route: "userDetail/update/info",
    params: {
      name:"",
      email:"",
      gender: "",
      dob: "",
      height: "",
      heightUnit: "",
      weight: "",
      weightUnit: "",
      waist: "",
      waistUnit: "",
      address:"",
    },
    queryParams: [],
    authRequired: true,
    method: "post",
    tag: "User Detail",
  },
  {
    route: "userDetail/add/report-detail",
    params: {
      heart_rate: "",
      blood_glucose: "",
      spo2: "",
      hrv: "",
      bmi: "",
      blood_pressure: "",
      overall_health: "",
      // error: "",
    },
    queryParams: [],
    authRequired: true,
    method: "post",
    tag: "User Detail",
  },
];
